class PakistanCities {
  // Major cities across Pakistan
  static const List<String> cities = [
    // Punjab
    'Lahore',
    'Faisalabad',
    'Rawalpindi',
    'Multan',
    'Gujranwala',
    'Sialkot',
    'Sargodha',
    'Bahawalpur',
    'Jhang',
    'Sheikhupura',
    'Gujrat',
    'Kasur',
    'Rahim Yar Khan',
    'Sahiwal',
    'Okara',
    'Wah Cantt',
    'Dera Ghazi Khan',
    'Mirpur',
    'Kamoke',
    'Mandi Bahauddin',
    'Jhelum',
    'Sadiqabad',
    'Khanewal',
    'Hafizabad',
    'Muzaffargarh',
    'Khanpur',
    
    // Sindh
    'Karachi',
    'Hyderabad',
    'Sukkur',
    'Larkana',
    'Nawabshah',
    'Mirpurkhas',
    'Jacobabad',
    'Shikarpur',
    'Khairpur',
    'Dadu',
    'Thatta',
    'Badin',
    'Umerkot',
    'Tando Adam',
    'Tando Allahyar',
    
    // Khyber Pakhtunkhwa
    'Peshawar',
    'Mardan',
    'Abbottabad',
    'Mingora',
    'Kohat',
    'Dera Ismail Khan',
    'Swabi',
    'Charsadda',
    'Nowshera',
    'Mansehra',
    'Bannu',
    'Haripur',
    'Karak',
    'Swat',
    
    // Balochistan
    'Quetta',
    'Turbat',
    'Khuzdar',
    'Hub',
    'Chaman',
    'Zhob',
    'Gwadar',
    'Sibi',
    'Loralai',
    'Mastung',
    
    // Islamabad Capital Territory
    'Islamabad',
    
    // Azad Jammu & Kashmir
    'Muzaffarabad',
    'Mirpur',
    'Kotli',
    'Rawalakot',
    'Bhimber',
    
    // Gilgit-Baltistan
    'Gilgit',
    'Skardu',
    'Hunza',
    'Chilas',
  ];

  // Areas for major cities
  static const Map<String, List<String>> cityAreas = {
    'Karachi': [
      'Clifton',
      'DHA',
      'Defence',
      'Gulshan-e-Iqbal',
      'North Nazimabad',
      'Saddar',
      'Tariq Road',
      'Malir',
      'Korangi',
      'Landhi',
      'Gulistan-e-Johar',
      'Bahadurabad',
      'PECHS',
      'Bahria Town',
      'Scheme 33',
      'North Karachi',
      'Surjani Town',
      'Lyari',
      'Orangi Town',
      'Federal B Area',
    ],
    'Lahore': [
      'DHA',
      'Defence',
      'Gulberg',
      'Model Town',
      'Johar Town',
      'Cantt',
      'Township',
      'Bahria Town',
      'Allama Iqbal Town',
      'Faisal Town',
      'Garden Town',
      'Iqbal Town',
      'Raiwind',
      'Wapda Town',
      'Cavalry Ground',
      'EME Society',
      'PWD Housing Scheme',
      'Shadman',
      'Muslim Town',
      'Samanabad',
    ],
    'Islamabad': [
      'F-6',
      'F-7',
      'F-8',
      'F-10',
      'F-11',
      'G-6',
      'G-7',
      'G-8',
      'G-9',
      'G-10',
      'G-11',
      'I-8',
      'I-9',
      'I-10',
      'Blue Area',
      'DHA',
      'Bahria Town',
      'Gulberg Greens',
      'PWD Housing Scheme',
      'Diplomatic Enclave',
    ],
    'Rawalpindi': [
      'Saddar',
      'Commercial Market',
      'Chaklala',
      'Bahria Town',
      'DHA',
      'Westridge',
      'Satellite Town',
      'Gulzar-e-Quaid',
      'PWD Housing Scheme',
      'Gulraiz Housing Scheme',
      'Askari',
      'Lalazar',
      'Raja Bazaar',
      'Committee Chowk',
    ],
    'Faisalabad': [
      'Peoples Colony',
      'D Ground',
      'Samanabad',
      'Jinnah Colony',
      'Madina Town',
      'Gulberg',
      'Model Town',
      'Millat Town',
      'Susan Road',
      'Canal Road',
    ],
    'Multan': [
      'Cantt',
      'Gulgasht Colony',
      'Bosan Road',
      'Model Town',
      'Shah Rukn-e-Alam Colony',
      'New Multan',
      'Shalimar Colony',
      'DHA',
      'Bahauddin Zakariya University Area',
    ],
    'Peshawar': [
      'Hayatabad',
      'University Town',
      'Saddar',
      'Cantt',
      'Regi Model Town',
      'Gulbahar',
      'Bara Gate',
      'Dalazak Road',
      'GT Road',
    ],
    'Quetta': [
      'Cantt',
      'Satellite Town',
      'Samungli Road',
      'Brewery Road',
      'Jinnah Town',
      'Zarghoon Road',
      'Airport Road',
    ],
    'Hyderabad': [
      'Latifabad',
      'Qasimabad',
      'Cantonment',
      'Auto Bhan Road',
      'Hali Road',
      'Liaquat Colony',
    ],
    'Gujranwala': [
      'Satellite Town',
      'Model Town',
      'Peoples Colony',
      'Civil Lines',
      'Cantt',
      'DC Colony',
    ],
    'Sialkot': [
      'Cantt',
      'Allama Iqbal Town',
      'Defence Road',
      'Model Town',
      'Paris Road',
      'Kutchery Road',
    ],
  };

  // Get areas for a specific city, returns empty list if city not found
  static List<String> getAreasForCity(String city) {
    return cityAreas[city] ?? [];
  }

  // Check if a city has predefined areas
  static bool hasAreas(String city) {
    return cityAreas.containsKey(city) && cityAreas[city]!.isNotEmpty;
  }
}
